<?php

/**
 * Libellés et regroupement UI pour les permissions (Spatie / config roles).
 * Clés = noms de permissions (identiques en base).
 */
return [
    'groups' => [
        'Système & rôles' => [
            'roles.manage_permissions' => 'Configurer les permissions par rôle',
        ],
        'Utilisateurs' => [
            'users.list' => 'Voir la liste des utilisateurs',
            'users.create' => 'Créer des utilisateurs',
            'users.edit' => 'Modifier des utilisateurs',
            'users.delete' => 'Supprimer des utilisateurs',
            'users.assign-role' => 'Attribuer ou changer le rôle d’un utilisateur',
            'users.view-own' => 'Voir les profils (périmètre entreprise)',
            'users.list-own' => 'Lister les utilisateurs (périmètre entreprise)',
        ],
        'Menus & plats' => [
            'menus.create' => 'Créer des menus',
            'menus.edit' => 'Modifier tout menu',
            'menus.delete' => 'Supprimer tout menu',
            'menus.view' => 'Voir tout menu (admin)',
            'menus.approve' => 'Approuver des menus',
            'menus.reject' => 'Rejeter des menus',
            'menus.list' => 'Lister tous les menus',
            'menus.edit-own' => 'Modifier ses propres menus',
            'menus.delete-own' => 'Supprimer ses propres menus',
            'menus.view-own' => 'Voir ses propres menus',
            'menus.list-own' => 'Lister ses propres menus',
            'menus.view-approved' => 'Voir les menus approuvés',
            'menus.list-approved' => 'Parcourir les menus approuvés',
        ],
        'Commandes' => [
            'orders.change-status' => 'Changer le statut d’une commande (cuisine / périmètre autorisé)',
            'orders.create' => 'Créer des commandes',
            'orders.edit' => 'Modifier des commandes',
            'orders.delete' => 'Supprimer des commandes',
            'orders.view' => 'Voir les commandes (vue étendue admin)',
            'orders.list' => 'Lister toutes les commandes',
            'orders.cancel' => 'Annuler des commandes',
            'orders.view-own' => 'Voir ses commandes',
            'orders.list-own' => 'Lister ses commandes',
            'orders.cancel-own' => 'Annuler ses commandes',
            'orders.view-own-menus' => 'Voir commandes liées à ses menus',
            'orders.list-own-menus' => 'Lister commandes liées à ses menus',
            'orders.view-assignments' => 'Voir ses livraisons assignées',
            'orders.list-assignments' => 'Lister ses livraisons',
            'orders.update-delivery-status' => 'Mettre à jour le statut de livraison',
            'orders.validate-delivery-code' => 'Valider un code de livraison',
            'orders.assign-livreur' => 'Assigner un livreur à une commande',
            'livreur.assignments.view-all' => 'Voir toutes les missions / flux livraisons (secrétariat)',
        ],
        'Promotions' => [
            'promotions.create' => 'Créer des promotions',
            'promotions.edit' => 'Modifier des promotions',
            'promotions.delete' => 'Supprimer des promotions',
            'promotions.view' => 'Voir les promotions',
            'promotions.claim' => 'Réclamer une promotion',
            'promotions.list' => 'Lister les promotions',
            'promotions.validate-ticket' => 'Valider un ticket promotion',
            'promotions.manage' => 'Gestion complète des réclamations / promotions (admin)',
        ],
        'Statistiques' => [
            'stats.admin.view' => 'Statistiques tableau de bord admin',
            'stats.client.view' => 'Statistiques client',
            'stats.cuisinier.view' => 'Statistiques cuisine',
            'stats.livreur.view' => 'Statistiques livreur',
            'stats.verificateur.view' => 'Statistiques vérificateur',
            'stats.entreprise.view' => 'Statistiques entreprise',
            'stats.secretaire.view' => 'Statistiques secrétariat',
        ],
        'Abonnements particuliers' => [
            'subscriptions.create' => 'Créer un abonnement',
            'subscriptions.edit' => 'Modifier des abonnements',
            'subscriptions.delete' => 'Supprimer des abonnements',
            'subscriptions.list' => 'Lister les abonnements',
            'subscriptions.cancel-own' => 'Annuler son abonnement',
            'subscriptions.view-own' => 'Voir ses abonnements',
            'subscriptions.list-own' => 'Lister ses abonnements (entreprise)',
        ],
        'Modules admin (back-office)' => [
            'admin.companies' => 'Entreprises B2B (liste, validation, édition)',
            'admin.payments' => 'Paiements & rapprochement',
            'admin.reports' => 'Rapports exportables',
            'admin.deliveries' => 'Livraisons (suivi global)',
            'admin.event-requests' => 'Demandes événementielles',
            'admin.event-types' => 'Types d’événements (configuration)',
            'admin.notifications.broadcast' => 'Envoyer des annonces / notifications',
            'admin.subscription-plans' => 'Plans d’abonnement',
            'admin.subscriptions' => 'Abonnements clients (validation, pause…)',
            'admin.company-subscriptions' => 'Abonnements B2B (activation…)',
            'admin.operational' => 'Vue exploitation abonnements (admin)',
            'admin.agents' => 'Approbation des agents entreprise',
            'admin.exports' => 'Exports PDF / CSV (agents, livraisons…)',
        ],
        'Exploitation cuisine' => [
            'operational.subscriptions.view' => 'Vue exploitation abonnements & repas (cuisine)',
        ],
        'Portail agent entreprise' => [
            'agent.dashboard' => 'Accès tableau de bord agent',
            'agent.meal-plans' => 'Voir / gérer ses choix de repas',
        ],
        'Entreprise B2B' => [
            'entreprise.b2b.access' => 'Accès portail entreprise (abonnements, employés, demandes agents)',
            'company.employees.manage' => 'Importer / gérer les employés de son entreprise',
            'b2b.meal-plans.manage' => 'Créer ou supprimer des plans de repas employés (périmètre entreprise)',
        ],
    ],
];
